// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtAk_wBhu8HoQBY9SUGGEAv8mk8Kxdk4o',
    appId: '1:569298672847:web:4d1d1d7ac10679a3e42bba',
    messagingSenderId: '569298672847',
    projectId: 'travel-app-a01eb',
    authDomain: 'travel-app-a01eb.firebaseapp.com',
    storageBucket: 'travel-app-a01eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11RU3OkYZg4x6mh2n-Y14E4uEnmA6JVE',
    appId: '1:569298672847:android:5b8e8052d3bbe39ee42bba',
    messagingSenderId: '569298672847',
    projectId: 'travel-app-a01eb',
    storageBucket: 'travel-app-a01eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBflbsNl1PAhRo6LVjTV0wUwthsZKkoqNY',
    appId: '1:569298672847:ios:3f5ab925a9f5774ce42bba',
    messagingSenderId: '569298672847',
    projectId: 'travel-app-a01eb',
    storageBucket: 'travel-app-a01eb.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );
}
